format = """
[â–‘â–’â–“](#a3aed2)\
$os\
$username\
[î‚´ ](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´ ](fg:#769ff0 bg:#394260)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[î‚´ ](fg:#394260 bg:#212736)\
$aws\
$gcloud\
$azure\
[î‚´ ](fg:#212736 bg:#1d2230)\
$docker_context\
[î‚´ ](fg:#1d2230 bg:#1d2230)\
$kubernetes\
[î‚´ ](fg:#1d2230 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
\n$shell\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#a3aed2"
style_root = "bg:#a3aed2"
format = '[$user ]($style)'
disabled = true

[character]
format = "$symbol "
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold green)"
vimcmd_visual_symbol = "[â®](bold yellow)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_replace_one_symbol = "[â®](bold purple)"
disabled = false

[shell]
format = "[$indicator]($style) "
bash_indicator = "$"
fish_indicator = "ğŸŸ"
zsh_indicator = "âš¡"
powershell_indicator = ""
ion_indicator = "ï¼©"
elvish_indicator = "ï¼¥"
tcsh_indicator = "ï¼´"
nu_indicator = "ğŸ”†"
xonsh_indicator = "xsh"
cmd_indicator = "cmd"
unknown_indicator = ""
style = "white bold"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#a3aed2"
disabled = false # Disabled by default

[os.symbols]
AIX = " â¿ "
Alpaquita = " ğŸ”” "
AlmaLinux = " ğŸ’  "
Alpine = " ğŸ”ï¸ "
Amazon = " ğŸ™‚ "
Android = " ğŸ¤– "
Arch = " ğŸ—ï¸ "
Artix = " ğŸ—ï¸ "
Bluefin = " ğŸŸ "
CachyOS = " ğŸ—ï¸ "
CentOS = " ğŸ’  "
Debian = " ğŸŒ€ "
DragonFly = " ğŸ‰ "
Emscripten = " ğŸ”— "
EndeavourOS = " ğŸš€ "
Fedora = " ğŸ© "
FreeBSD = " ğŸ˜ˆ "
Garuda = " ğŸ¦… "
Gentoo = " ğŸ—œï¸ "
HardenedBSD = " ğŸ›¡ï¸ "
Illumos = " ğŸ¦ "
Kali = " ğŸ‰ "
Linux = " ğŸ§ "
Mabox = " ğŸ“¦ "
Macos = " îœ‘ "
Manjaro = " ğŸ¥­ "
Mariner = " ğŸŒŠ "
MidnightBSD = " ğŸŒ˜ "
Mint = " ğŸŒ¿ "
NetBSD = " ğŸš© "
NixOS = " â„ï¸ "
Nobara = " ğŸ© "
OpenBSD = " ğŸ¡ "
OpenCloudOS = " â˜ï¸ "
openEuler = " ğŸ¦‰ "
openSUSE = " ğŸ¦ "
OracleLinux = " ğŸ¦´ "
Pop = " ğŸ­ "
Raspbian = " ğŸ“ "
Redhat = " ğŸ© "
RedHatEnterprise = " ğŸ© "
RockyLinux = " ğŸ’  "
Redox = " ğŸ§ª "
Solus = " â›µ "
SUSE = " ğŸ¦ "
Ubuntu = " ğŸ¯ "
Ultramarine = " ğŸ”· "
Unknown = " â“ "
Uos = " ğŸ² "
Void = " îŠ™  "
Windows = " ğŸªŸ "

[directory]
style = "bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"git" = "ï‡“ "
"code" = "ï‡“ "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
style = "bg:#394260"
format = "[on $symbol$branch(:$remote_branch) ]($style)"
symbol = "î‚  "
# style = "bold purple"
truncation_length = 20
truncation_symbol = "â€¦"
only_attached = false
# always_show_remote = false
ignore_branches = []
disabled = false

[git_commit]
style = "green bold bg:#394260"
commit_hash_length = 7
format = '[\($hash$tag\)]($style)'
# style = "green bold"
only_detached = true
disabled = false
tag_symbol = " ğŸ·  "
tag_disabled = true
tag_max_candidates = 0

[git_metrics]
# style = "bg:#394260"
added_style = "bold green bg:#394260"
deleted_style = "bold red bg:#394260"
only_nonzero_diffs = true
format = "([+$added]($added_style))([-$deleted]($deleted_style))"
disabled = true
ignore_submodules = false

[git_state]
style = "bold yellow bg:#394260"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
# style = "bold yellow"
format = '\([$state($progress_current/$progress_total)]($style)\)'
disabled = false

[git_status]
style = "red bold bg:#394260"
format = '[$all_status$ahead_behind]($style)'
# style = "red bold"
stashed = '\$'
ahead = "â‡¡"
behind = "â‡£"
up_to_date = ""
diverged = "â‡•"
conflicted = "="
deleted = "âœ˜"
renamed = "Â»"
modified = "!"
staged = "+"
untracked = "?"
typechanged = ""
ignore_submodules = false
disabled = false
use_git_executable = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[ â™¥ $time ]($style)'

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = "â˜ï¸ "
style = "bold yellow bg:#212736"
disabled = false
expiration_symbol = "X"
force_display = false
detect_env_vars = ["AWS_PROFILE", "AWS_DEFAULT_PROFILE", "AWS_REGION", "AWS_DEFAULT_REGION"]

[aws.region_aliases]

[aws.profile_aliases]

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = "â˜ï¸ "
style = "bold blue bg:#212736"
disabled = false
detect_env_vars = ["CLOUDSDK_CONFIG", "CLOUDSDK_PROJECT", "CLOUDSDK_COMPUTE_REGION"]

[gcloud.region_aliases]

[gcloud.project_aliases]

[azure]
format = "on [$symbol($subscription)]($style) "
symbol = "â˜ï¸ "
style = "blue bold bg:#212736"
disabled = true
detect_env_vars = ["AZURE_CONFIG_DIR", "AZURE_DEFAULT_SUBSCRIPTION"]

[azure.subscription_aliases]

[kubernetes]
symbol = "â˜¸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "bg:#1d2230"
disabled = false

